import {
  Link as LinkIcon, MessageSquare, Video, Music, Phone, MessageCircle,
  FormInput, Navigation, Eye, CalendarPlus, Ticket, CheckSquare, ShoppingCart,
  BadgePercent, MapPin, Package, MessagesSquare, BarChart3, Mail, CalendarCheck,
  Images, ClipboardList, Quote, Utensils, BookOpen, Briefcase, Trophy, Star, ShoppingBag,
  BookText, GalleryHorizontal,
} from "lucide-react";

export type InteractionDef = {
  id: string;
  label: string;
  icon: any;
  short: string;
  details: string;
};

/** Submit-job sentinel when the client wants staff to pick interactions. */
export const STAFF_CHOICE_ID = "staff_choice";

export function interactionLabel(id: string): string {
  if (id === STAFF_CHOICE_ID) return "I'd rather you choose for me";
  return INTERACTIONS.find((i) => i.id === id)?.label ?? id;
}

export const INTERACTIONS: InteractionDef[] = [
  { id: "open_url", label: "Open URL", icon: LinkIcon,
    short: "Send taps to any web link.",
    details: "Tap a flyer element to open a website, social profile, menu, store page or any URL — in a new tab or in the same window." },
  { id: "popup", label: "Show popup", icon: MessageSquare,
    short: "Reveal a message or details on tap.",
    details: "Display a custom popup with rich text, images, terms, descriptions or special offers without leaving the flyer." },
  { id: "video", label: "Play video", icon: Video,
    short: "Embed YouTube, Vimeo or hosted video.",
    details: "Tap to play a video right inside the flyer — perfect for trailers, intros, testimonials and product demos." },
  { id: "audio", label: "Play audio", icon: Music,
    short: "Background music, voice notes, audio ads.",
    details: "Attach an audio clip that plays when the flyer opens or when a specific element is tapped." },
  { id: "call", label: "Call phone", icon: Phone,
    short: "One-tap call to your business.",
    details: "Tap to dial your phone number directly from the user's device — no copying needed." },
  { id: "sms", label: "Send SMS", icon: MessageCircle,
    short: "Pre-filled text message.",
    details: "Open the user's SMS app with your number and message pre-filled — great for keywords, RSVPs and quick orders." },
  { id: "form", label: "Capture form", icon: FormInput,
    short: "Collect names, emails, phone numbers and more.",
    details: "Build a custom form with any fields you need. Submissions are stored in your dashboard and exportable." },
  { id: "go_page", label: "Go to page", icon: Navigation,
    short: "Jump between pages of a multi-page flyer.",
    details: "Turn your flyer into a mini-site with navigable pages — menu, gallery, info, contact, etc." },
  { id: "reveal", label: "Reveal layer", icon: Eye,
    short: "Hide-and-show effect.",
    details: "Tap to reveal hidden content like a coupon code, secret menu item or surprise offer." },
  { id: "calendar", label: "Add to calendar", icon: CalendarPlus,
    short: "Save your event to their calendar.",
    details: "One-tap save of date, time, location and description into Apple, Google or Outlook calendar." },
  { id: "ticket", label: "Buy ticket", icon: Ticket,
    short: "Sell event tickets right from the flyer.",
    details: "Connect a ticket link or use built-in checkout to sell tickets with quantity options and pricing tiers." },
  { id: "rsvp", label: "RSVP", icon: CheckSquare,
    short: "Collect attendance for your event.",
    details: "Visitors RSVP with name and email. You see who's coming in your dashboard." },
  { id: "checkout", label: "Link to checkout", icon: ShoppingCart,
    short: "Send taps to your store checkout.",
    details: "Connect Stripe, Shopify, Square or any checkout link so taps go straight to a paid action." },
  { id: "coupon", label: "Coupon", icon: BadgePercent,
    short: "Reveal and copy a discount code.",
    details: "Display a discount, copy the code with one tap and optionally redirect to your store." },
  { id: "maps", label: "Open in maps (GPS)", icon: MapPin,
    short: "Tap for directions.",
    details: "Open Apple Maps, Google Maps or Waze with your address pre-loaded for instant turn-by-turn directions." },
  { id: "buy_product", label: "Buy product", icon: Package,
    short: "Sell individual products.",
    details: "Showcase a product with image, price and a buy button that completes the transaction." },
  { id: "product_grid", label: "Multi-product shop", icon: ShoppingBag,
    short: "Sell up to 12 products in one popup.",
    details: "Open a 12-product shop popup. Each item has image, price, description and optional sizes (S–6XL). Buyers add to the flyer's shared cart and check out via Venmo / Cash App / Apple Cash." },
  { id: "air", label: "Air messages (chat bubbles)", icon: MessagesSquare,
    short: "Animated chat bubbles surface tips and offers.",
    details: "Floating message bubbles appear as visitors browse — ideal for promos, FAQs or helpful prompts." },
  { id: "poll", label: "Poll", icon: BarChart3,
    short: "Ask a question, collect votes.",
    details: "Multiple-choice poll with live results. Great for engagement and feedback collection." },
  { id: "subscribe", label: "Subscribe (email signup)", icon: Mail,
    short: "Build your mailing list.",
    details: "Capture emails into a named list. Export anytime or send mass emails from your dashboard." },
  { id: "appointment", label: "Book appointment", icon: CalendarCheck,
    short: "Let visitors pick a time slot.",
    details: "Built-in scheduler with availability windows, time zones and confirmation emails." },
  { id: "gallery", label: "Photo gallery", icon: Images,
    short: "Swipeable photo set.",
    details: "Tap an image to open a full-screen, swipeable gallery — menu photos, portfolio, event highlights." },
  { id: "carousel", label: "Carousel (video + flyers)", icon: GalleryHorizontal,
    short: "Scrolling multi-view gallery.",
    details: "A scrolling gallery where the first card can be a video and the rest are flyers — each card has its own title, subtitle and call-to-action button." },
  { id: "survey", label: "Survey", icon: ClipboardList,
    short: "Ask multiple questions, collect answers.",
    details: "Multi-question survey with text, multiple-choice and star-rating questions. Responses appear in your dashboard." },
  { id: "testimonial", label: "Testimonials", icon: Quote,
    short: "Collect and display visitor reviews.",
    details: "Visitors leave a star rating + written review. Moderate them in your dashboard before they appear publicly." },
  { id: "reserve_table", label: "Reserve a table", icon: Utensils,
    short: "Restaurant table reservations.",
    details: "Built-in reservation form with date, time slots and party size. Bookings appear in your dashboard." },
  { id: "schedule_consultation", label: "Schedule consultation", icon: Briefcase,
    short: "Let visitors book a consultation.",
    details: "Visitors choose a topic, duration and time — perfect for coaches, advisors and service providers." },
  { id: "show_menu", label: "Show menu", icon: BookOpen,
    short: "Open a beautifully formatted menu page.",
    details: "Build sections (Starters, Mains, Drinks…) with items, prices and descriptions. Visitors tap to open." },
  { id: "join_challenge", label: "Join challenge", icon: Trophy,
    short: "Sign visitors up for a challenge.",
    details: "Create a challenge with title, dates, goal and rules. Visitors join with name + email; participants appear in your dashboard." },
  { id: "business_rating", label: "Business rating (5 stars)", icon: Star,
    short: "Show average rating, collect star votes.",
    details: "Displays your average rating + a tap-to-rate widget so visitors can rate your business 1–5 stars." },
  { id: "novel", label: "Novel / Story (paid chapters)", icon: BookText,
    short: "Serialized book with free preview + PayPal unlock.",
    details: "Paste your manuscript with # Chapter markers — the book is split into chapters. First chapters are free; readers unlock the rest (per-chapter or full bundle) via PayPal. Includes free follow + paid subscribe to author." },
];
