project_id = "iwmykqilqywbzxpcgaop"

[functions.portal-access]
verify_jwt = false

[functions.novel-paypal-ipn]
verify_jwt = false

[functions.marketing-trigger]
verify_jwt = true

[functions.marketing-draft-complete]
verify_jwt = false
