project_id = "iwmykqilqywbzxpcgaop"

[functions.portal-access]
verify_jwt = false

[functions.novel-paypal-ipn]
verify_jwt = false

[functions.marketing-trigger]
verify_jwt = true

[functions.marketing-draft-complete]
verify_jwt = false

[functions.meta-connect-start]
verify_jwt = true

[functions.meta-post-now]
verify_jwt = true

[functions.meta-instagram-post-now]
verify_jwt = true

[functions.meta-post-scheduled]
verify_jwt = false

[functions.meta-oauth-start]
verify_jwt = true

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-instagram-token-extend]
verify_jwt = true
